swagger: "2.0"
info:
  title: API Title
  version: "1.0"
host: ppm.tekoapis.com
consumes:
  - application/json
produces:
  - application/json
schemes:
  - https
paths:
  /api/vouchers:
    get:
      summary: Get vouchers of one platform
      operationId: GetVouchersUrl
      responses:
        '200':
          description: A successful response.
          schema:
            $ref: '#/definitions/GetVouchersResponse'
        default:
          description: An unexpected error response
          schema:
            $ref: '#/definitions/runtimeError'
      parameters:
        - name: platform_code
          description: code of a platform
          in: query
          required: true
          type: string
        - name: voucher_status
          type: string
          description: filter status of voucher
          in: query
          required: false
        - name: voucher_type
          type: string
          description: filter type of voucher
          in: query
          required: false
        - name: query
          description: can query voucher_code, example voucher_code=ABC filter name contains 'ABC'
          in: query
          required: false
          type: string
      tags:
        - PPMExternalAPI

  /api/voucher/{voucher_code}:
    get:
      summary: Get voucher detail
      operationId: GetVoucherDetailUrl
      responses:
        '200':
          description: A successful response.
          schema:
            $ref: '#/definitions/GetVoucherDetailResponse'
        default:
          description: An unexpected error response
          schema:
            $ref: '#/definitions/runtimeError'
      parameters:
        - name: voucher_code
          description: code of a voucher
          in: path
          required: true
          type: string
        - name: promotion_id
          description: promotion that the voucher can be applied
          in: query
          required: false
          type: string
      tags:
        - PPMExternalAPI

  /api/assign-customer:
    post:
      summary: aa
      operationId: AssignCustomerToVoucherUrl
      responses:
        '200':
          description: A successful response.
          schema:
            $ref: '#/definitions/AssignCustomerResponse'
        default:
          description: An unexpected error response
          schema:
            $ref: '#/definitions/runtimeError'
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/AssignCustomerRequest'
      tags:
        - PPMExternalAPI

definitions:
  GetVoucherDetailResponse:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
      results:
        $ref: '#/definitions/VoucherDetail'

  GetVouchersResponse:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
      results:
        type: array
        items:
          $ref: '#/definitions/VoucherDetail'
        title: results

  VoucherDetail:
    type: object
    properties:
      code:
        type: string
        description: Code of the voucher
      description:
        type: string
        description: Name/description of voucher
      status:
        type: string
        description: Status of voucher
      validFrom:
        type: string
        format: date-time
        description: Voucher can be use from time
      validTo:
        type: string
        format: date-time
        description: Voucher can be use before time
      discountPercent:
        type: number
        description: Discount percent
      maxDiscountAmount:
        type: number
        description: For case discount fix amount, discount percent=100%, max Discount Amount=discount Amount
      appliedTerminals:
        type: array
        items:
          type: string
          description: list terminal's code that voucher can be applied
      appliedPromotions:
        type: array
        items:
          type: number
          description: list promotion ids that voucher can be applied
  AssignCustomerRequest:
    type: object
    properties:
      voucherCode:
        type: string
      phones:
        type: array
        items:
          type: string
      fromTime:
        type: string
        format: date-time
        description: phone number can be use voucher from time(optional)
      toTime:
        type: string
        format: date-time
        description: phone number can be use voucher before(optional)
  AssignCustomerResponse:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
      results:
        type: object
        properties:
          appliedPromotions:
            type: array
            description: promotion that phone number was assined
            items:
              type: number
        title: results

  runtimeError:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
      results:
        type: object
